spring:
  application:
    name: app-item
  datasource:
    url: jdbc:mysql://localhost:3306/clouddemo
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@127.0.0.1:9090/eureka,http://root:123456@127.0.0.1:9091/eureka,http://root:123456@127.0.0.1:9191/eureka
####因为该应用是一个服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
####是否需要从eureka上检索服务
    fetch-registry: true